seed: 42
device: cuda
wandb:
  enabled: true
  project: distrib_diffusion


optimal_transport_training: true

model:
  class_name: SimpleModelSinTime
  params:
    input_dim: 2
    hidden_dim: 128
    activation: silu

optimizer:
  name: adamw
  params:
    lr: 2.0e-3
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1.0e-8

training:
  train_steps: 10000
  batch_size: 256
  log_interval: 100
  eval_interval: 500
  img_log_interval: 2000

scheduler:
  class_name: FlowScheduler
  params:
    num_steps: 10
    shift: 1.0
    device: cuda
